Select O_ORDERKEY as ORDERKEY,O_CUSTKEY as CUSTKEY,O_ORDERSTATUS as ORDERSTATUS
,O_TOTALPRICE as TOTALPRICE,O_ORDERDATE as ORDERDATE
--, O_ORDERPRIORITY as ORDERPRIORITY, O_SHIPPRIORITY as SHIPPRIORITY
From SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS